window.include(
	'/resources/',
	[
		'js/jquery.min',
		'js/jquery.mousewheel.min',
		'plugin/datepicker/jquery-ui.custom.min',
		'plugin/fancybox/jquery.fancybox.pack',
		'js/library',
		'js/action'
	]
);